export type ReconCategory = "trending" | "cafes" | "nightlife" | "pop";

export type MockCityItem = {
  id: string;
  category: ReconCategory;
  title: string;
  placeName: string;
  neighborhood: string;
  lat: number;
  lng: number;
  description: string;
  timeWindow: string;
  activityScore: number;
  postCount: number;
  crowdLevel: "low" | "medium" | "high";
  tags: string[];
};

const rawMockCityData: MockCityItem[] = [
  {
    id: "trend-001",
    category: "trending",
    title: "Crowd building near the seawall",
    placeName: "English Bay",
    neighborhood: "West End",
    lat: 49.2866,
    lng: -123.1426,
    description: "Multiple posts mention sunset crowds, buskers, and packed benches near the water.",
    timeWindow: "Now",
    activityScore: 94,
    postCount: 42,
    crowdLevel: "high",
    tags: ["sunset", "walk", "crowd", "waterfront"],
  },
  {
    id: "trend-002",
    category: "trending",
    title: "Street activity around Granville",
    placeName: "Granville Street",
    neighborhood: "Downtown",
    lat: 49.2807,
    lng: -123.1207,
    description: "Posts show busy sidewalks, food runs, and people moving between bars and venues.",
    timeWindow: "Tonight",
    activityScore: 91,
    postCount: 38,
    crowdLevel: "high",
    tags: ["downtown", "street", "busy", "late"],
  },
  {
    id: "trend-003",
    category: "trending",
    title: "Photos around the steam clock",
    placeName: "Gastown Steam Clock",
    neighborhood: "Gastown",
    lat: 49.2844,
    lng: -123.1089,
    description: "Tourist clips and street photography posts are clustering around the main Gastown strip.",
    timeWindow: "Today",
    activityScore: 83,
    postCount: 29,
    crowdLevel: "medium",
    tags: ["photos", "tourists", "gastown", "walk"],
  },
  {
    id: "trend-004",
    category: "trending",
    title: "Lineups near Rogers Arena",
    placeName: "Rogers Arena",
    neighborhood: "Downtown",
    lat: 49.2778,
    lng: -123.1088,
    description: "Several posts mention people gathering near arena entrances and surrounding restaurants.",
    timeWindow: "Tonight",
    activityScore: 89,
    postCount: 35,
    crowdLevel: "high",
    tags: ["arena", "lineup", "event", "downtown"],
  },
  {
    id: "trend-005",
    category: "trending",
    title: "UBC campus activity picking up",
    placeName: "UBC Main Mall",
    neighborhood: "UBC",
    lat: 49.2677,
    lng: -123.2523,
    description: "Campus posts show study groups, club tables, and food traffic around central walkways.",
    timeWindow: "Afternoon",
    activityScore: 76,
    postCount: 21,
    crowdLevel: "medium",
    tags: ["campus", "students", "study", "food"],
  },
  {
    id: "trend-006",
    category: "trending",
    title: "Weekend walkers in Stanley Park",
    placeName: "Stanley Park Seawall",
    neighborhood: "Stanley Park",
    lat: 49.3017,
    lng: -123.1417,
    description: "Posts show bike traffic, tourists, and waterfront clips around the seawall.",
    timeWindow: "Weekend",
    activityScore: 87,
    postCount: 31,
    crowdLevel: "high",
    tags: ["seawall", "bikes", "tourists", "outdoors"],
  },
  {
    id: "trend-007",
    category: "trending",
    title: "Robson shopping crowd",
    placeName: "Robson Street",
    neighborhood: "Downtown",
    lat: 49.2856,
    lng: -123.1247,
    description: "Shopping posts and food clips are concentrated along Robson between Burrard and Bute.",
    timeWindow: "Today",
    activityScore: 81,
    postCount: 27,
    crowdLevel: "medium",
    tags: ["shopping", "food", "downtown", "crowd"],
  },
  {
    id: "trend-008",
    category: "trending",
    title: "Rain reports near Science World",
    placeName: "Science World",
    neighborhood: "False Creek",
    lat: 49.2734,
    lng: -123.1038,
    description: "Posts mention wet paths, umbrellas, and slower foot traffic near the seawall.",
    timeWindow: "Now",
    activityScore: 73,
    postCount: 19,
    crowdLevel: "medium",
    tags: ["rain", "science world", "walk", "weather"],
  },
  {
    id: "trend-009",
    category: "trending",
    title: "Mount Pleasant food crawl",
    placeName: "Main Street",
    neighborhood: "Mount Pleasant",
    lat: 49.2636,
    lng: -123.1006,
    description: "Food posts are clustering around casual restaurants, bakeries, and late afternoon coffee spots.",
    timeWindow: "Evening",
    activityScore: 84,
    postCount: 30,
    crowdLevel: "medium",
    tags: ["food", "main street", "cafes", "dinner"],
  },
  {
    id: "trend-010",
    category: "trending",
    title: "Kits beach volleyball crowd",
    placeName: "Kitsilano Beach",
    neighborhood: "Kitsilano",
    lat: 49.2754,
    lng: -123.1541,
    description: "Clips show beach volleyball, groups sitting near the grass, and sunset photos.",
    timeWindow: "Evening",
    activityScore: 88,
    postCount: 33,
    crowdLevel: "high",
    tags: ["beach", "volleyball", "sunset", "kits"],
  },
  {
    id: "trend-011",
    category: "trending",
    title: "BC Place crowd movement",
    placeName: "BC Place",
    neighborhood: "Downtown",
    lat: 49.2768,
    lng: -123.1119,
    description: "Posts show people moving around the stadium, nearby bars, and transit entrances.",
    timeWindow: "Tonight",
    activityScore: 86,
    postCount: 32,
    crowdLevel: "high",
    tags: ["stadium", "crowd", "transit", "event"],
  },
  {
    id: "trend-012",
    category: "trending",
    title: "Commercial Drive patio posts",
    placeName: "Commercial Drive",
    neighborhood: "Grandview-Woodland",
    lat: 49.2694,
    lng: -123.0696,
    description: "Posts mention patio tables, small restaurants, and music coming from nearby venues.",
    timeWindow: "Evening",
    activityScore: 79,
    postCount: 24,
    crowdLevel: "medium",
    tags: ["patio", "food", "music", "drive"],
  },
  {
    id: "trend-013",
    category: "trending",
    title: "Coal Harbour photo traffic",
    placeName: "Coal Harbour",
    neighborhood: "Coal Harbour",
    lat: 49.2907,
    lng: -123.1277,
    description: "Photo posts around the marina and waterfront walkway are increasing.",
    timeWindow: "Today",
    activityScore: 71,
    postCount: 18,
    crowdLevel: "medium",
    tags: ["photos", "marina", "waterfront", "walk"],
  },

  {
    id: "cafe-001",
    category: "cafes",
    title: "Study tables filling up",
    placeName: "Nemesis Coffee GNW",
    neighborhood: "Mount Pleasant",
    lat: 49.2674,
    lng: -123.0916,
    description: "Posts show laptops, packed tables, and steady coffee traffic.",
    timeWindow: "Afternoon",
    activityScore: 82,
    postCount: 26,
    crowdLevel: "medium",
    tags: ["coffee", "study", "laptop", "pastries"],
  },
  {
    id: "cafe-002",
    category: "cafes",
    title: "Brunch coffee crowd",
    placeName: "Revolver",
    neighborhood: "Gastown",
    lat: 49.2833,
    lng: -123.1068,
    description: "Multiple posts show espresso drinks, sidewalk traffic, and short waits.",
    timeWindow: "Morning",
    activityScore: 79,
    postCount: 22,
    crowdLevel: "medium",
    tags: ["espresso", "gastown", "brunch", "coffee"],
  },
  {
    id: "cafe-003",
    category: "cafes",
    title: "Quiet tables near Kits",
    placeName: "Their There",
    neighborhood: "Kitsilano",
    lat: 49.2687,
    lng: -123.1556,
    description: "Posts mention coffee, breakfast sandwiches, and a calmer late morning crowd.",
    timeWindow: "Morning",
    activityScore: 72,
    postCount: 17,
    crowdLevel: "medium",
    tags: ["kits", "coffee", "breakfast", "quiet"],
  },
  {
    id: "cafe-004",
    category: "cafes",
    title: "Bakery line outside",
    placeName: "Small Victory",
    neighborhood: "Yaletown",
    lat: 49.2758,
    lng: -123.1214,
    description: "Posts show pastry trays, coffee cups, and a short line near the counter.",
    timeWindow: "Morning",
    activityScore: 84,
    postCount: 28,
    crowdLevel: "high",
    tags: ["bakery", "pastry", "coffee", "yaletown"],
  },
  {
    id: "cafe-005",
    category: "cafes",
    title: "Late afternoon coffee stop",
    placeName: "Prototype Coffee",
    neighborhood: "Strathcona",
    lat: 49.2815,
    lng: -123.0927,
    description: "Posts mention pour-over flights, small groups, and steady afternoon traffic.",
    timeWindow: "Afternoon",
    activityScore: 75,
    postCount: 18,
    crowdLevel: "medium",
    tags: ["pour over", "coffee", "quiet", "strathcona"],
  },
  {
    id: "cafe-006",
    category: "cafes",
    title: "Aesthetic cafe posts rising",
    placeName: "Aperture Coffee Bar",
    neighborhood: "Mount Pleasant",
    lat: 49.2622,
    lng: -123.1017,
    description: "Posts show coffee, window seats, and casual meetups around Main Street.",
    timeWindow: "Today",
    activityScore: 70,
    postCount: 16,
    crowdLevel: "low",
    tags: ["main street", "coffee", "window seat", "casual"],
  },
  {
    id: "cafe-007",
    category: "cafes",
    title: "Campus coffee rush",
    placeName: "Great Dane Coffee",
    neighborhood: "UBC",
    lat: 49.2669,
    lng: -123.2498,
    description: "Student posts show coffee lines and study sessions near campus buildings.",
    timeWindow: "Afternoon",
    activityScore: 78,
    postCount: 23,
    crowdLevel: "medium",
    tags: ["ubc", "students", "study", "coffee"],
  },
  {
    id: "cafe-008",
    category: "cafes",
    title: "Dessert and coffee clips",
    placeName: "Thierry",
    neighborhood: "Downtown",
    lat: 49.2846,
    lng: -123.1246,
    description: "Posts show cakes, espresso drinks, and people stopping in near Robson.",
    timeWindow: "Evening",
    activityScore: 81,
    postCount: 25,
    crowdLevel: "medium",
    tags: ["dessert", "robson", "coffee", "date"],
  },
  {
    id: "cafe-009",
    category: "cafes",
    title: "Minimal cafe interior posts",
    placeName: "Kafka's Coffee",
    neighborhood: "Mount Pleasant",
    lat: 49.2631,
    lng: -123.1012,
    description: "Posts mention open tables, simple coffee orders, and quiet conversations.",
    timeWindow: "Today",
    activityScore: 69,
    postCount: 15,
    crowdLevel: "low",
    tags: ["coffee", "quiet", "main street", "work"],
  },
  {
    id: "cafe-010",
    category: "cafes",
    title: "Matcha and pastries",
    placeName: "Paragon Tea Room",
    neighborhood: "Cambie Village",
    lat: 49.2534,
    lng: -123.1154,
    description: "Posts show matcha drinks, pastries, and a relaxed afternoon crowd.",
    timeWindow: "Afternoon",
    activityScore: 74,
    postCount: 19,
    crowdLevel: "medium",
    tags: ["matcha", "tea", "pastry", "afternoon"],
  },
  {
    id: "cafe-011",
    category: "cafes",
    title: "Coffee near the seawall",
    placeName: "Honolulu Coffee",
    neighborhood: "Coal Harbour",
    lat: 49.2902,
    lng: -123.1247,
    description: "Posts show coffee walks, waterfront photos, and quick stops before the seawall.",
    timeWindow: "Morning",
    activityScore: 67,
    postCount: 13,
    crowdLevel: "low",
    tags: ["waterfront", "coffee", "walk", "coal harbour"],
  },
  {
    id: "cafe-012",
    category: "cafes",
    title: "Cute date cafe mentions",
    placeName: "Cafe Portrait",
    neighborhood: "West End",
    lat: 49.2861,
    lng: -123.1348,
    description: "Posts mention portrait art, coffee dates, and small-table seating.",
    timeWindow: "Evening",
    activityScore: 77,
    postCount: 20,
    crowdLevel: "medium",
    tags: ["date", "coffee", "art", "west end"],
  },
  {
    id: "cafe-013",
    category: "cafes",
    title: "Breakfast line on Main",
    placeName: "49th Parallel Cafe",
    neighborhood: "Mount Pleasant",
    lat: 49.2557,
    lng: -123.1013,
    description: "Posts show donuts, coffee cups, and steady morning traffic.",
    timeWindow: "Morning",
    activityScore: 85,
    postCount: 30,
    crowdLevel: "high",
    tags: ["donuts", "coffee", "breakfast", "main street"],
  },
  {
    id: "night-001",
    category: "nightlife",
    title: "Line forming before doors",
    placeName: "Commodore Ballroom",
    neighborhood: "Downtown",
    lat: 49.2801,
    lng: -123.1207,
    description: "Posts show people gathering outside before a show near Granville.",
    timeWindow: "Tonight",
    activityScore: 92,
    postCount: 41,
    crowdLevel: "high",
    tags: ["show", "line", "granville", "music"],
  },
  {
    id: "night-002",
    category: "nightlife",
    title: "Late crowd near Fortune",
    placeName: "Fortune Sound Club",
    neighborhood: "Chinatown",
    lat: 49.2802,
    lng: -123.1002,
    description: "Posts mention music, groups arriving, and busy sidewalks nearby.",
    timeWindow: "Late night",
    activityScore: 86,
    postCount: 32,
    crowdLevel: "high",
    tags: ["club", "music", "late", "chinatown"],
  },
  {
    id: "night-003",
    category: "nightlife",
    title: "Gastown cocktail traffic",
    placeName: "The Diamond",
    neighborhood: "Gastown",
    lat: 49.2837,
    lng: -123.1045,
    description: "Posts show cocktails, small groups, and evening traffic around Powell and Carrall.",
    timeWindow: "Tonight",
    activityScore: 80,
    postCount: 24,
    crowdLevel: "medium",
    tags: ["cocktails", "gastown", "date", "bar"],
  },
  {
    id: "night-004",
    category: "nightlife",
    title: "Patio drinks on Commercial",
    placeName: "Havana Vancouver",
    neighborhood: "Commercial Drive",
    lat: 49.2708,
    lng: -123.0695,
    description: "Posts mention patio drinks, music, and people moving along the Drive.",
    timeWindow: "Evening",
    activityScore: 78,
    postCount: 22,
    crowdLevel: "medium",
    tags: ["patio", "drinks", "commercial drive", "music"],
  },
  {
    id: "night-005",
    category: "nightlife",
    title: "Club strip getting busy",
    placeName: "Granville Entertainment District",
    neighborhood: "Downtown",
    lat: 49.2789,
    lng: -123.1222,
    description: "Posts show people moving between bars, food spots, and clubs.",
    timeWindow: "Late night",
    activityScore: 95,
    postCount: 48,
    crowdLevel: "high",
    tags: ["clubs", "bars", "granville", "crowd"],
  },
  {
    id: "pop-001",
    category: "pop",
    title: "Pop-up vintage market",
    placeName: "The Beaumont Studios",
    neighborhood: "Mount Pleasant",
    lat: 49.2644,
    lng: -123.0956,
    description: "Mock posts mention racks of vintage clothing, local sellers, and short entry lines.",
    timeWindow: "Weekend",
    activityScore: 88,
    postCount: 34,
    crowdLevel: "high",
    tags: ["pop-up", "vintage", "market", "shopping"],
  },
  {
    id: "pop-002",
    category: "pop",
    title: "Temporary dessert stand",
    placeName: "Robson Square",
    neighborhood: "Downtown",
    lat: 49.2827,
    lng: -123.1211,
    description: "Mock posts show dessert boxes, people stopping by, and short social clips.",
    timeWindow: "Today",
    activityScore: 76,
    postCount: 20,
    crowdLevel: "medium",
    tags: ["pop-up", "dessert", "robson", "food"],
  },
  {
    id: "pop-003",
    category: "pop",
    title: "Streetwear drop nearby",
    placeName: "Gastown",
    neighborhood: "Gastown",
    lat: 49.2838,
    lng: -123.1067,
    description: "Mock posts mention a small streetwear release and people checking nearby shops.",
    timeWindow: "Today",
    activityScore: 82,
    postCount: 28,
    crowdLevel: "medium",
    tags: ["streetwear", "drop", "shopping", "gastown"],
  },

  {
    id: "cafe-003",
    category: "cafes",
    title: "Quiet tables near Kits",
    placeName: "Their There",
    neighborhood: "Kitsilano",
    lat: 49.2687,
    lng: -123.1556,
    description: "Posts mention coffee, breakfast sandwiches, and a calmer late morning crowd.",
    timeWindow: "Morning",
    activityScore: 72,
    postCount: 17,
    crowdLevel: "medium",
    tags: ["kits", "coffee", "breakfast", "quiet"],
  },
  {
    id: "cafe-004",
    category: "cafes",
    title: "Bakery line outside",
    placeName: "Small Victory",
    neighborhood: "Yaletown",
    lat: 49.2758,
    lng: -123.1214,
    description: "Posts show pastry trays, coffee cups, and a short line near the counter.",
    timeWindow: "Morning",
    activityScore: 84,
    postCount: 28,
    crowdLevel: "high",
    tags: ["bakery", "pastry", "coffee", "yaletown"],
  },
  {
    id: "cafe-005",
    category: "cafes",
    title: "Late afternoon coffee stop",
    placeName: "Prototype Coffee",
    neighborhood: "Strathcona",
    lat: 49.2815,
    lng: -123.0927,
    description: "Posts mention pour-over flights, small groups, and steady afternoon traffic.",
    timeWindow: "Afternoon",
    activityScore: 75,
    postCount: 18,
    crowdLevel: "medium",
    tags: ["pour over", "coffee", "quiet", "strathcona"],
  },
  {
    id: "cafe-006",
    category: "cafes",
    title: "Aesthetic cafe posts rising",
    placeName: "Aperture Coffee Bar",
    neighborhood: "Mount Pleasant",
    lat: 49.2622,
    lng: -123.1017,
    description: "Posts show coffee, window seats, and casual meetups around Main Street.",
    timeWindow: "Today",
    activityScore: 70,
    postCount: 16,
    crowdLevel: "low",
    tags: ["main street", "coffee", "window seat", "casual"],
  },
  {
    id: "cafe-007",
    category: "cafes",
    title: "Campus coffee rush",
    placeName: "Great Dane Coffee",
    neighborhood: "UBC",
    lat: 49.2669,
    lng: -123.2498,
    description: "Student posts show coffee lines and study sessions near campus buildings.",
    timeWindow: "Afternoon",
    activityScore: 78,
    postCount: 23,
    crowdLevel: "medium",
    tags: ["ubc", "students", "study", "coffee"],
  },
  {
    id: "cafe-008",
    category: "cafes",
    title: "Dessert and coffee clips",
    placeName: "Thierry",
    neighborhood: "Downtown",
    lat: 49.2846,
    lng: -123.1246,
    description: "Posts show cakes, espresso drinks, and people stopping in near Robson.",
    timeWindow: "Evening",
    activityScore: 81,
    postCount: 25,
    crowdLevel: "medium",
    tags: ["dessert", "robson", "coffee", "date"],
  },
  {
    id: "cafe-009",
    category: "cafes",
    title: "Minimal cafe interior posts",
    placeName: "Kafka's Coffee",
    neighborhood: "Mount Pleasant",
    lat: 49.2631,
    lng: -123.1012,
    description: "Posts mention open tables, simple coffee orders, and quiet conversations.",
    timeWindow: "Today",
    activityScore: 69,
    postCount: 15,
    crowdLevel: "low",
    tags: ["coffee", "quiet", "main street", "work"],
  },
  {
    id: "cafe-010",
    category: "cafes",
    title: "Matcha and pastries",
    placeName: "Paragon Tea Room",
    neighborhood: "Cambie Village",
    lat: 49.2534,
    lng: -123.1154,
    description: "Posts show matcha drinks, pastries, and a relaxed afternoon crowd.",
    timeWindow: "Afternoon",
    activityScore: 74,
    postCount: 19,
    crowdLevel: "medium",
    tags: ["matcha", "tea", "pastry", "afternoon"],
  },
  {
    id: "cafe-011",
    category: "cafes",
    title: "Coffee near the seawall",
    placeName: "Honolulu Coffee",
    neighborhood: "Coal Harbour",
    lat: 49.2902,
    lng: -123.1247,
    description: "Posts show coffee walks, waterfront photos, and quick stops before the seawall.",
    timeWindow: "Morning",
    activityScore: 67,
    postCount: 13,
    crowdLevel: "low",
    tags: ["waterfront", "coffee", "walk", "coal harbour"],
  },
  {
    id: "cafe-012",
    category: "cafes",
    title: "Cute date cafe mentions",
    placeName: "Cafe Portrait",
    neighborhood: "West End",
    lat: 49.2861,
    lng: -123.1348,
    description: "Posts mention portrait art, coffee dates, and small-table seating.",
    timeWindow: "Evening",
    activityScore: 77,
    postCount: 20,
    crowdLevel: "medium",
    tags: ["date", "coffee", "art", "west end"],
  },
  {
    id: "cafe-013",
    category: "cafes",
    title: "Breakfast line on Main",
    placeName: "49th Parallel Cafe",
    neighborhood: "Mount Pleasant",
    lat: 49.2557,
    lng: -123.1013,
    description: "Posts show donuts, coffee cups, and steady morning traffic.",
    timeWindow: "Morning",
    activityScore: 85,
    postCount: 30,
    crowdLevel: "high",
    tags: ["donuts", "coffee", "breakfast", "main street"],
  },
  {
    id: "night-001",
    category: "nightlife",
    title: "Line forming before doors",
    placeName: "Commodore Ballroom",
    neighborhood: "Downtown",
    lat: 49.2801,
    lng: -123.1207,
    description: "Posts show people gathering outside before a show near Granville.",
    timeWindow: "Tonight",
    activityScore: 92,
    postCount: 41,
    crowdLevel: "high",
    tags: ["show", "line", "granville", "music"],
  },
  {
    id: "night-002",
    category: "nightlife",
    title: "Late crowd near Fortune",
    placeName: "Fortune Sound Club",
    neighborhood: "Chinatown",
    lat: 49.2802,
    lng: -123.1002,
    description: "Posts mention music, groups arriving, and busy sidewalks nearby.",
    timeWindow: "Late night",
    activityScore: 86,
    postCount: 32,
    crowdLevel: "high",
    tags: ["club", "music", "late", "chinatown"],
  },
  {
    id: "night-003",
    category: "nightlife",
    title: "Gastown cocktail traffic",
    placeName: "The Diamond",
    neighborhood: "Gastown",
    lat: 49.2837,
    lng: -123.1045,
    description: "Posts show cocktails, small groups, and evening traffic around Powell and Carrall.",
    timeWindow: "Tonight",
    activityScore: 80,
    postCount: 24,
    crowdLevel: "medium",
    tags: ["cocktails", "gastown", "date", "bar"],
  },
  {
    id: "night-004",
    category: "nightlife",
    title: "Patio drinks on Commercial",
    placeName: "Havana Vancouver",
    neighborhood: "Commercial Drive",
    lat: 49.2708,
    lng: -123.0695,
    description: "Posts mention patio drinks, music, and people moving along the Drive.",
    timeWindow: "Evening",
    activityScore: 78,
    postCount: 22,
    crowdLevel: "medium",
    tags: ["patio", "drinks", "commercial drive", "music"],
  },
  {
    id: "night-005",
    category: "nightlife",
    title: "Club strip getting busy",
    placeName: "Granville Entertainment District",
    neighborhood: "Downtown",
    lat: 49.2789,
    lng: -123.1222,
    description: "Posts show people moving between bars, food spots, and clubs.",
    timeWindow: "Late night",
    activityScore: 95,
    postCount: 48,
    crowdLevel: "high",
    tags: ["clubs", "bars", "granville", "crowd"],
  },
  {
    id: "night-006",
    category: "nightlife",
    title: "Live music mentions",
    placeName: "The Biltmore Cabaret",
    neighborhood: "Mount Pleasant",
    lat: 49.2582,
    lng: -123.1018,
    description: "Posts mention a show, small venue crowd, and nearby bar traffic.",
    timeWindow: "Tonight",
    activityScore: 82,
    postCount: 27,
    crowdLevel: "medium",
    tags: ["live music", "mount pleasant", "show", "bar"],
  },
  {
    id: "night-007",
    category: "nightlife",
    title: "Yaletown dinner-to-drinks crowd",
    placeName: "Yaletown",
    neighborhood: "Yaletown",
    lat: 49.2766,
    lng: -123.1206,
    description: "Posts show dinner groups turning into bar traffic around Hamilton and Mainland.",
    timeWindow: "Tonight",
    activityScore: 84,
    postCount: 29,
    crowdLevel: "medium",
    tags: ["dinner", "drinks", "yaletown", "groups"],
  },
  {
    id: "night-008",
    category: "nightlife",
    title: "Karaoke room posts",
    placeName: "Fantacity Karaoke",
    neighborhood: "Downtown",
    lat: 49.2784,
    lng: -123.1252,
    description: "Posts show group karaoke, private rooms, and late-night plans.",
    timeWindow: "Late night",
    activityScore: 74,
    postCount: 18,
    crowdLevel: "medium",
    tags: ["karaoke", "group", "late", "downtown"],
  },
  {
    id: "night-009",
    category: "nightlife",
    title: "Arcade bar activity",
    placeName: "Glitch Retro Arcade Bar",
    neighborhood: "Kitsilano",
    lat: 49.2648,
    lng: -123.1681,
    description: "Posts mention games, drinks, and casual groups before midnight.",
    timeWindow: "Tonight",
    activityScore: 71,
    postCount: 16,
    crowdLevel: "medium",
    tags: ["arcade", "bar", "games", "kits"],
  },
  {
    id: "night-010",
    category: "nightlife",
    title: "Speakeasy-style drinks",
    placeName: "Key Party",
    neighborhood: "Mount Pleasant",
    lat: 49.2576,
    lng: -123.1008,
    description: "Posts mention cocktails, small groups, and low-key nightlife near Main.",
    timeWindow: "Tonight",
    activityScore: 73,
    postCount: 17,
    crowdLevel: "low",
    tags: ["cocktails", "date", "main street", "low key"],
  },
  {
    id: "pop-001",
    category: "pop",
    title: "Pop-up vintage market",
    placeName: "The Beaumont Studios",
    neighborhood: "Mount Pleasant",
    lat: 49.2644,
    lng: -123.0956,
    description: "Mock posts mention racks of vintage clothing, local sellers, and short entry lines.",
    timeWindow: "Weekend",
    activityScore: 88,
    postCount: 34,
    crowdLevel: "high",
    tags: ["pop-up", "vintage", "market", "shopping"],
  },
  {
    id: "pop-002",
    category: "pop",
    title: "Temporary dessert stand",
    placeName: "Robson Square",
    neighborhood: "Downtown",
    lat: 49.2827,
    lng: -123.1211,
    description: "Mock posts show dessert boxes, people stopping by, and short social clips.",
    timeWindow: "Today",
    activityScore: 76,
    postCount: 20,
    crowdLevel: "medium",
    tags: ["pop-up", "dessert", "robson", "food"],
  },
  {
    id: "pop-003",
    category: "pop",
    title: "Streetwear drop nearby",
    placeName: "Gastown",
    neighborhood: "Gastown",
    lat: 49.2838,
    lng: -123.1067,
    description: "Mock posts mention a small streetwear release and people checking nearby shops.",
    timeWindow: "Today",
    activityScore: 82,
    postCount: 28,
    crowdLevel: "medium",
    tags: ["streetwear", "drop", "shopping", "gastown"],
  },
  {
    id: "pop-004",
    category: "pop",
    title: "Campus club booth cluster",
    placeName: "UBC Nest",
    neighborhood: "UBC",
    lat: 49.2665,
    lng: -123.2493,
    description: "Mock posts show booths, flyers, snacks, and student groups in the main building.",
    timeWindow: "Afternoon",
    activityScore: 74,
    postCount: 19,
    crowdLevel: "medium",
    tags: ["campus", "club", "booth", "students"],
  },
  {
    id: "pop-005",
    category: "pop",
    title: "Creator meetup clips",
    placeName: "Olympic Village",
    neighborhood: "False Creek",
    lat: 49.2707,
    lng: -123.1059,
    description: "Mock posts show small creator groups filming near the waterfront.",
    timeWindow: "Evening",
    activityScore: 79,
    postCount: 25,
    crowdLevel: "medium",
    tags: ["creator", "meetup", "waterfront", "video"],
  },
  {
    id: "pop-006",
    category: "pop",
    title: "Mini art sale",
    placeName: "Granville Island",
    neighborhood: "Fairview",
    lat: 49.2712,
    lng: -123.1340,
    description: "Mock posts mention prints, handmade goods, and a small crowd near market walkways.",
    timeWindow: "Weekend",
    activityScore: 85,
    postCount: 31,
    crowdLevel: "high",
    tags: ["art", "market", "prints", "granville island"],
  },
  {
    id: "pop-007",
    category: "pop",
    title: "Photo booth pop-up",
    placeName: "Pacific Centre",
    neighborhood: "Downtown",
    lat: 49.2833,
    lng: -123.1189,
    description: "Mock posts show friends taking photo strips and posting mall clips.",
    timeWindow: "Today",
    activityScore: 68,
    postCount: 14,
    crowdLevel: "low",
    tags: ["photo booth", "mall", "friends", "downtown"],
  },
  {
    id: "pop-008",
    category: "pop",
    title: "Outdoor brand sample table",
    placeName: "Kitsilano Beach",
    neighborhood: "Kitsilano",
    lat: 49.2754,
    lng: -123.1541,
    description: "Mock posts mention a small sample table near the beach path.",
    timeWindow: "Afternoon",
    activityScore: 72,
    postCount: 17,
    crowdLevel: "medium",
    tags: ["brand", "sample", "beach", "pop-up"],
  },
  {
    id: "pop-009",
    category: "pop",
    title: "Record swap setup",
    placeName: "Red Cat Records",
    neighborhood: "Mount Pleasant",
    lat: 49.2637,
    lng: -123.1001,
    description: "Mock posts show vinyl crates, music fans, and a small sidewalk crowd.",
    timeWindow: "Weekend",
    activityScore: 80,
    postCount: 26,
    crowdLevel: "medium",
    tags: ["records", "music", "swap", "main street"],
  },
  {
    id: "pop-010",
    category: "pop",
    title: "Food truck cluster",
    placeName: "Vancouver Art Gallery",
    neighborhood: "Downtown",
    lat: 49.2829,
    lng: -123.1205,
    description: "Mock posts show food trucks, lunch lines, and people eating near the plaza.",
    timeWindow: "Lunch",
    activityScore: 83,
    postCount: 29,
    crowdLevel: "high",
    tags: ["food trucks", "lunch", "plaza", "downtown"],
  },
  {
    id: "pop-011",
    category: "pop",
    title: "Indie zine table",
    placeName: "Commercial Drive",
    neighborhood: "Grandview-Woodland",
    lat: 49.2694,
    lng: -123.0696,
    description: "Mock posts mention small press zines, handmade stickers, and local art tables.",
    timeWindow: "Weekend",
    activityScore: 69,
    postCount: 15,
    crowdLevel: "low",
    tags: ["zine", "stickers", "local art", "drive"],
  },
  {
    id: "pop-012",
    category: "pop",
    title: "Sneaker meetup",
    placeName: "Yaletown Roundhouse",
    neighborhood: "Yaletown",
    lat: 49.2734,
    lng: -123.1216,
    description: "Mock posts show sneaker photos, outfit checks, and small groups meeting nearby.",
    timeWindow: "Evening",
    activityScore: 75,
    postCount: 18,
    crowdLevel: "medium",
    tags: ["sneakers", "meetup", "style", "yaletown"],
  },
];

export const mockCityData: MockCityItem[] = Array.from(
  new Map(rawMockCityData.map((item) => [item.id, item])).values()
);

export default mockCityData;
