import type { Pin } from "../types/pin";

export type PinMeta = { street: string; attendees: number; imageUrl: string };

export const PIN_META: Record<string, PinMeta> = {
  "mock-001": { street: "Stanley Park Dr", attendees: 8,   imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
  "mock-002": { street: "Burrard St",       attendees: 5,   imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
  "mock-003": { street: "Terminal Ave",     attendees: 34,  imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=300&q=80" },
  "mock-004": { street: "Granville St",     attendees: 94,  imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
  "mock-005": { street: "Cornwall Ave",     attendees: 47,  imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=300&q=80" },
  "mock-006": { street: "Pacific Blvd",     attendees: 112, imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
  "mock-007": { street: "Water St",         attendees: 23,  imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
  "mock-008": { street: "Beatty St",        attendees: 78,  imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
  "mock-009": { street: "University Blvd",  attendees: 15,  imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
  "mock-010": { street: "Granville Bridge", attendees: 31,  imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80" },
};

// Timestamps relative to a fixed reference so relative-time labels stay sensible.
const REF = new Date("2026-06-02T18:00:00Z").getTime();
const ago = (mins: number) => new Date(REF - mins * 60_000).toISOString();
const ttl = (mins: number) => new Date(REF + mins * 60_000).toISOString();

export const mockPins: Pin[] = [
  {
    postId: "mock-001",
    source: "X",
    postUrl: "https://x.com/VanWeather/status/mock-001",
    creatorHandle: "@VanWeather",
    text: "Heavy rain moving into Stanley Park, NW winds picking up to 40 km/h. Trail conditions deteriorating fast.",
    category: "weather",
    placeName: "Stanley Park",
    lat: 49.3043,
    lng: -123.1443,
    createdAt: ago(8),
    fetchedAt: ago(7),
    expiresAt: ttl(240),
    locationConfidence: 0.95,
    status: "active",
  },
  {
    postId: "mock-002",
    source: "X",
    postUrl: "https://x.com/VanAlert/status/mock-002",
    creatorHandle: "@VanAlert",
    text: "Vehicle break-in near Robson and Burrard. Police on scene. Don't leave valuables visible.",
    category: "crime_safety",
    placeName: "Robson Street",
    lat: 49.2838,
    lng: -123.125,
    createdAt: ago(22),
    fetchedAt: ago(20),
    expiresAt: ttl(120),
    locationConfidence: 0.88,
    status: "active",
  },
  {
    postId: "mock-003",
    source: "X",
    postUrl: "https://x.com/VanFoodScene/status/mock-003",
    creatorHandle: "@VanFoodScene",
    text: "Lineup at the Science World farmers market is already wrapping around the building. Get here early.",
    category: "daily_life",
    placeName: "Science World",
    lat: 49.2734,
    lng: -123.1034,
    createdAt: ago(45),
    fetchedAt: ago(43),
    expiresAt: ttl(360),
    locationConfidence: 0.92,
    status: "active",
  },
  {
    postId: "mock-004",
    source: "X",
    postUrl: "https://x.com/VanNight/status/mock-004",
    creatorHandle: "@VanNight",
    text: "Sold out show at the Commodore tonight. Line forming at 7pm, doors at 8. Coat check is cash only.",
    category: "special_events",
    placeName: "Commodore Ballroom",
    lat: 49.2786,
    lng: -123.1217,
    createdAt: ago(12),
    fetchedAt: ago(10),
    expiresAt: ttl(480),
    locationConfidence: 0.97,
    status: "active",
  },
  {
    postId: "mock-005",
    source: "X",
    postUrl: "https://x.com/KitsLocal/status/mock-005",
    creatorHandle: "@KitsLocal",
    text: "Kits Beach fully packed today. Volleyball courts full by 11am. Water is cold but people are in.",
    category: "daily_life",
    placeName: "Kitsilano Beach",
    lat: 49.2738,
    lng: -123.1567,
    createdAt: ago(30),
    fetchedAt: ago(28),
    expiresAt: ttl(300),
    locationConfidence: 0.91,
    status: "active",
  },
  {
    postId: "mock-006",
    source: "X",
    postUrl: "https://x.com/VanSports/status/mock-006",
    creatorHandle: "@VanSports",
    text: "Canucks playoff warmup in 2hrs at Rogers Arena. Area getting heavy already, Pacific Blvd backed up.",
    category: "special_events",
    placeName: "Rogers Arena",
    lat: 49.2778,
    lng: -123.1088,
    createdAt: ago(18),
    fetchedAt: ago(16),
    expiresAt: ttl(360),
    locationConfidence: 0.99,
    status: "active",
  },
  {
    postId: "mock-007",
    source: "X",
    postUrl: "https://x.com/GastownCo/status/mock-007",
    creatorHandle: "@GastownCo",
    text: "Steam clock malfunction again. Tourists backing up on Water St, minor foot traffic congestion around the block.",
    category: "locations",
    placeName: "Gastown",
    lat: 49.2837,
    lng: -123.1085,
    createdAt: ago(5),
    fetchedAt: ago(4),
    expiresAt: ttl(180),
    locationConfidence: 0.93,
    status: "active",
  },
  {
    postId: "mock-008",
    source: "X",
    postUrl: "https://x.com/BCPlaceWatch/status/mock-008",
    creatorHandle: "@BCPlaceWatch",
    text: "BC Place gates opening early tonight. Lot C already 40% full. Bridge St exit backed up.",
    category: "special_events",
    placeName: "BC Place",
    lat: 49.2776,
    lng: -123.112,
    createdAt: ago(35),
    fetchedAt: ago(33),
    expiresAt: ttl(420),
    locationConfidence: 0.98,
    status: "active",
  },
  {
    postId: "mock-009",
    source: "X",
    postUrl: "https://x.com/UBCStudent/status/mock-009",
    creatorHandle: "@UBCStudent",
    text: "University Blvd closed between Agronomy and Main Mall for utility work. Campus shuttle on alternate loop.",
    category: "crime_safety",
    placeName: "UBC",
    lat: 49.2606,
    lng: -123.246,
    createdAt: ago(55),
    fetchedAt: ago(53),
    expiresAt: ttl(240),
    locationConfidence: 0.85,
    status: "active",
  },
  {
    postId: "mock-010",
    source: "X",
    postUrl: "https://x.com/GranvilleLocal/status/mock-010",
    creatorHandle: "@GranvilleLocal",
    text: "Granville Bridge closed southbound for maintenance until midnight. Use Cambie or Burrard as alternate.",
    category: "locations",
    placeName: "Granville Street",
    lat: 49.2757,
    lng: -123.136,
    createdAt: ago(15),
    fetchedAt: ago(13),
    expiresAt: ttl(360),
    locationConfidence: 0.9,
    status: "active",
  },
];
