import type { DashboardData } from "../types/dashboard";

export const mockDashboard: DashboardData = {
  today: {
    timeBlocks: [
      { block: "morning",    label: "Morning",    hours: "6am – 12pm", count: 5  },
      { block: "afternoon",  label: "Afternoon",  hours: "12pm – 6pm", count: 9  },
      { block: "evening",    label: "Evening",    hours: "6pm – 10pm", count: 14 },
      { block: "late-night", label: "Late night", hours: "10pm – 2am", count: 8  },
    ],
    events: [
      { id: "td-m1", title: "Granville Island farmers market", venue: "Granville Island",            area: "Kitsilano",      timeBlock: "morning",    time: "8:30 AM" },
      { id: "td-m2", title: "Stanley Park 5k run",            venue: "Stanley Park Pavilion",       area: "Stanley Park",   timeBlock: "morning",    time: "7:00 AM" },
      { id: "td-m3", title: "UBC farmers market",             venue: "UBC Main Mall",               area: "UBC",            timeBlock: "morning",    time: "9:00 AM" },
      { id: "td-m4", title: "Morning yoga at Kits Beach",     venue: "Kitsilano Beach",             area: "Kitsilano",      timeBlock: "morning",    time: "7:30 AM" },
      { id: "td-m5", title: "Commercial Drive Sunday brunch", venue: "Commercial Drive",            area: "East Van",       timeBlock: "morning",    time: "10:00 AM" },
      { id: "td-a1", title: "Robson Square food trucks",      venue: "Robson Square",               area: "Downtown",       timeBlock: "afternoon",  time: "12:00 PM" },
      { id: "td-a2", title: "Vancouver Art Gallery drop-in",  venue: "Vancouver Art Gallery",       area: "Downtown",       timeBlock: "afternoon",  time: "1:00 PM" },
      { id: "td-a3", title: "Kits Beach volleyball open",     venue: "Kitsilano Beach",             area: "Kitsilano",      timeBlock: "afternoon",  time: "2:00 PM" },
      { id: "td-a4", title: "Mt Pleasant art walk",           venue: "Main Street",                 area: "Mount Pleasant", timeBlock: "afternoon",  time: "1:00 PM" },
      { id: "td-a5", title: "Gastown vintage pop-up",         venue: "Water Street",                area: "Gastown",        timeBlock: "afternoon",  time: "12:00 PM" },
      { id: "td-a6", title: "Yaletown market tables",         venue: "Mainland Street",             area: "Yaletown",       timeBlock: "afternoon",  time: "3:00 PM" },
      { id: "td-a7", title: "UBC public lecture series",      venue: "Chan Centre · UBC",           area: "UBC",            timeBlock: "afternoon",  time: "4:00 PM" },
      { id: "td-a8", title: "False Creek kayak rentals open", venue: "Granville Island",            area: "Kitsilano",      timeBlock: "afternoon",  time: "2:30 PM" },
      { id: "td-a9", title: "Strathcona mural tour",          venue: "Strathcona",                  area: "East Van",       timeBlock: "afternoon",  time: "1:30 PM" },
      { id: "td-e1", title: "Alex G + Slow Pulp",             venue: "Commodore Ballroom",          area: "Granville",      timeBlock: "evening",    time: "8:00 PM" },
      { id: "td-e2", title: "Jazz residency",                 venue: "Guilt & Co",                  area: "Gastown",        timeBlock: "evening",    time: "8:30 PM" },
      { id: "td-e3", title: "Canucks preseason",              venue: "Rogers Arena",                area: "Downtown",       timeBlock: "evening",    time: "7:30 PM" },
      { id: "td-e4", title: "DJ night",                       venue: "Rickshaw Theatre",            area: "Gastown",        timeBlock: "evening",    time: "9:00 PM" },
      { id: "td-e5", title: "Rooftop bar opens season",       venue: "The Roof · Yaletown",        area: "Yaletown",       timeBlock: "evening",    time: "6:00 PM" },
      { id: "td-e6", title: "Pop-up supper club",             venue: "East Van Studios",            area: "Mount Pleasant", timeBlock: "evening",    time: "7:00 PM" },
      { id: "td-e7", title: "Comedy night",                   venue: "Biltmore Cabaret",            area: "Mount Pleasant", timeBlock: "evening",    time: "9:30 PM" },
      { id: "td-e8", title: "Drag show",                      venue: "Celebrities · Downtown",     area: "Downtown",       timeBlock: "evening",    time: "9:00 PM" },
      { id: "td-e9", title: "Tasting menu last seating",      venue: "Wildebeest",                 area: "Gastown",        timeBlock: "evening",    time: "9:00 PM" },
      { id: "td-e10", title: "Film screening",                venue: "Vancity Theatre",            area: "Granville",      timeBlock: "evening",    time: "7:00 PM" },
      { id: "td-e11", title: "Live soul set",                 venue: "Pat's Pub",                   area: "Downtown",       timeBlock: "evening",    time: "8:00 PM" },
      { id: "td-e12", title: "Night market kicks off",        venue: "Chinatown Night Market",     area: "Downtown",       timeBlock: "evening",    time: "6:30 PM" },
      { id: "td-e13", title: "Painting and wine evening",     venue: "Gastown studio",             area: "Gastown",        timeBlock: "evening",    time: "7:00 PM" },
      { id: "td-e14", title: "Spoken word open stage",        venue: "Café Deux Soleils",          area: "Commercial Dr",  timeBlock: "evening",    time: "8:00 PM" },
      { id: "td-l1", title: "Late DJ set",                    venue: "Fox Cabaret",                 area: "Mount Pleasant", timeBlock: "late-night", time: "11:00 PM" },
      { id: "td-l2", title: "Granville Strip peaks",          venue: "Multiple venues",             area: "Granville",      timeBlock: "late-night", time: "11:30 PM" },
      { id: "td-l3", title: "Late night ramen",               venue: "Marutama Ra-men",             area: "Robson",         timeBlock: "late-night", time: "11:00 PM" },
      { id: "td-l4", title: "Afterhours",                     venue: "Venue Nightclub",             area: "Granville",      timeBlock: "late-night", time: "12:00 AM" },
      { id: "td-l5", title: "Late bar program",               venue: "Wildebeest",                 area: "Gastown",        timeBlock: "late-night", time: "11:30 PM" },
      { id: "td-l6", title: "Karaoke last call",              venue: "Gastown spot",               area: "Gastown",        timeBlock: "late-night", time: "1:00 AM" },
      { id: "td-l7", title: "2am fried chicken",              venue: "Commercial Drive",           area: "East Van",       timeBlock: "late-night", time: "2:00 AM" },
      { id: "td-l8", title: "Last call downtown",             venue: "Multiple bars",              area: "Downtown",       timeBlock: "late-night", time: "2:00 AM" },
    ],
    categoryStats: [
      { key: "nightlife", label: "Nightlife", count: 34, description: "Bars, shows, clubs, late food. Multiple venues on Granville and Gastown at capacity by 10pm." },
      { key: "trending",  label: "Trending",  count: 26, description: "High-volume city activity across Downtown, Gastown, and Mt Pleasant. Rogers Arena driving foot traffic." },
      { key: "cafes",     label: "Cafes",     count: 22, description: "Coffee, study spots, brunch, bakeries. Rain driving heavy demand near UBC and Kitsilano." },
      { key: "popups",    label: "Pop-ups",   count: 18, description: "Markets, drops, temporary events. Granville Island market and Mt Pleasant art walk active until early evening." },
    ],
    weather: {
      condition: "Rain",
      conditionCode: "rain",
      temperature: 14,
      rainChance: 78,
      windSpeed: 18,
      visibility: "9 km",
      outdoorEventImpact: "high",
      hourlyForecast: [
        { hour: "6 PM",  temp: 14, conditionCode: "rain"       },
        { hour: "7 PM",  temp: 13, conditionCode: "rain"       },
        { hour: "8 PM",  temp: 13, conditionCode: "heavy-rain" },
        { hour: "9 PM",  temp: 12, conditionCode: "heavy-rain" },
        { hour: "10 PM", temp: 12, conditionCode: "heavy-rain" },
        { hour: "11 PM", temp: 11, conditionCode: "rain"       },
      ],
      affectedAreas: ["Stanley Park", "Kitsilano", "Granville Island", "Outdoor patios"],
      categoryImpacts: [
        { key: "cafes",    label: "Cafes",          impact: "positive", note: "Rain drives indoor demand. Longer queues at coffee spots near Downtown and UBC." },
        { key: "nightlife",label: "Nightlife",      impact: "neutral",  note: "Indoor venues unaffected. Outdoor lineups uncomfortable after 9pm." },
        { key: "popups",   label: "Pop-ups",        impact: "negative", note: "Granville Island market packing up early. Outdoor events winding down by 7pm." },
        { key: "outdoor",  label: "Outdoor events", impact: "negative", note: "High impact. Seawall and park trails wet after 8pm. Street programming affected." },
      ],
    },
    safetyItems: [
      { id: "sf1", type: "large-crowd",    typeLabel: "Large crowd",    area: "Downtown",       description: "Rogers Arena event crowd filling Pacific Blvd and Griffiths Way. 10,000+ expected.", time: "7 PM – 11 PM", severity: "high" },
      { id: "sf2", type: "police-activity",typeLabel: "Police activity",area: "Granville",      description: "Officers on foot patrol along Granville Strip. Above-average crowd volume expected after 10pm.", time: "After 10 PM", severity: "medium" },
      { id: "sf3", type: "road-closure",   typeLabel: "Road closure",   area: "Downtown",       description: "Robson Square water feature area closed for event setup. Pedestrian access via Hornby St.", time: "Until midnight", severity: "medium" },
      { id: "sf4", type: "event-congestion", typeLabel: "Event congestion", area: "Granville",  description: "Heavy foot traffic near Commodore Ballroom before and after Alex G show.", time: "7 PM – 10 PM", severity: "low" },
      { id: "sf5", type: "transit-entrance", typeLabel: "Transit delay", area: "Downtown",      description: "Waterfront Station main entrance may be congested. Use secondary entrance on Cordova.", time: "After 9 PM", severity: "low" },
    ],
  },

  tonight: {
    timeBlocks: [
      { block: "morning",    label: "Morning",    hours: "6am – 12pm", count: 0  },
      { block: "afternoon",  label: "Afternoon",  hours: "12pm – 6pm", count: 0  },
      { block: "evening",    label: "Evening",    hours: "6pm – 10pm", count: 14 },
      { block: "late-night", label: "Late night", hours: "10pm – 2am", count: 8  },
    ],
    events: [
      { id: "tn-e1", title: "Alex G + Slow Pulp",             venue: "Commodore Ballroom",          area: "Granville",      timeBlock: "evening",    time: "8:00 PM" },
      { id: "tn-e2", title: "Jazz residency",                 venue: "Guilt & Co",                  area: "Gastown",        timeBlock: "evening",    time: "8:30 PM" },
      { id: "tn-e3", title: "Canucks preseason",              venue: "Rogers Arena",                area: "Downtown",       timeBlock: "evening",    time: "7:30 PM" },
      { id: "tn-e4", title: "DJ night",                       venue: "Rickshaw Theatre",            area: "Gastown",        timeBlock: "evening",    time: "9:00 PM" },
      { id: "tn-e5", title: "Rooftop bar opens season",       venue: "The Roof · Yaletown",        area: "Yaletown",       timeBlock: "evening",    time: "6:00 PM" },
      { id: "tn-e6", title: "Pop-up supper club",             venue: "East Van Studios",            area: "Mount Pleasant", timeBlock: "evening",    time: "7:00 PM" },
      { id: "tn-e7", title: "Comedy night",                   venue: "Biltmore Cabaret",            area: "Mount Pleasant", timeBlock: "evening",    time: "9:30 PM" },
      { id: "tn-e8", title: "Drag show",                      venue: "Celebrities · Downtown",     area: "Downtown",       timeBlock: "evening",    time: "9:00 PM" },
      { id: "tn-e9", title: "Tasting menu last seating",      venue: "Wildebeest",                 area: "Gastown",        timeBlock: "evening",    time: "9:00 PM" },
      { id: "tn-e10", title: "Film screening",                venue: "Vancity Theatre",            area: "Granville",      timeBlock: "evening",    time: "7:00 PM" },
      { id: "tn-e11", title: "Live soul set",                 venue: "Pat's Pub",                   area: "Downtown",       timeBlock: "evening",    time: "8:00 PM" },
      { id: "tn-e12", title: "Night market kicks off",        venue: "Chinatown Night Market",     area: "Downtown",       timeBlock: "evening",    time: "6:30 PM" },
      { id: "tn-e13", title: "Painting and wine evening",     venue: "Gastown studio",             area: "Gastown",        timeBlock: "evening",    time: "7:00 PM" },
      { id: "tn-e14", title: "Spoken word open stage",        venue: "Café Deux Soleils",          area: "Commercial Dr",  timeBlock: "evening",    time: "8:00 PM" },
      { id: "tn-l1", title: "Late DJ set",                    venue: "Fox Cabaret",                 area: "Mount Pleasant", timeBlock: "late-night", time: "11:00 PM" },
      { id: "tn-l2", title: "Granville Strip peaks",          venue: "Multiple venues",             area: "Granville",      timeBlock: "late-night", time: "11:30 PM" },
      { id: "tn-l3", title: "Late night ramen",               venue: "Marutama Ra-men",             area: "Robson",         timeBlock: "late-night", time: "11:00 PM" },
      { id: "tn-l4", title: "Afterhours",                     venue: "Venue Nightclub",             area: "Granville",      timeBlock: "late-night", time: "12:00 AM" },
      { id: "tn-l5", title: "Late bar program",               venue: "Wildebeest",                 area: "Gastown",        timeBlock: "late-night", time: "11:30 PM" },
      { id: "tn-l6", title: "Karaoke last call",              venue: "Gastown spot",               area: "Gastown",        timeBlock: "late-night", time: "1:00 AM" },
      { id: "tn-l7", title: "2am fried chicken",              venue: "Commercial Drive",           area: "East Van",       timeBlock: "late-night", time: "2:00 AM" },
      { id: "tn-l8", title: "Last call downtown",             venue: "Multiple bars",              area: "Downtown",       timeBlock: "late-night", time: "2:00 AM" },
    ],
    categoryStats: [
      { key: "nightlife", label: "Nightlife", count: 42, description: "Bars, shows, clubs, late food. Heavy volume across Granville and Downtown expected after 10pm." },
      { key: "trending",  label: "Trending",  count: 28, description: "Rogers Arena at capacity. Elevated city-wide activity until midnight." },
      { key: "cafes",     label: "Cafes",     count: 18, description: "Heavy rain boosting coffee spot demand. Many staying open late tonight." },
      { key: "popups",    label: "Pop-ups",   count: 12, description: "Evening-only pop-ups in Gastown and Yaletown. Most outdoor options cancelled due to rain." },
    ],
    weather: {
      condition: "Heavy rain",
      conditionCode: "heavy-rain",
      temperature: 12,
      rainChance: 92,
      windSpeed: 24,
      visibility: "6 km",
      outdoorEventImpact: "high",
      hourlyForecast: [
        { hour: "6 PM",  temp: 12, conditionCode: "heavy-rain" },
        { hour: "7 PM",  temp: 12, conditionCode: "heavy-rain" },
        { hour: "8 PM",  temp: 11, conditionCode: "heavy-rain" },
        { hour: "9 PM",  temp: 11, conditionCode: "heavy-rain" },
        { hour: "10 PM", temp: 10, conditionCode: "heavy-rain" },
        { hour: "11 PM", temp: 10, conditionCode: "rain"       },
      ],
      affectedAreas: ["Stanley Park", "Kitsilano", "Granville Island", "All outdoor areas"],
      categoryImpacts: [
        { key: "cafes",    label: "Cafes",          impact: "positive", note: "Heaviest rain of the week drives peak indoor coffee demand." },
        { key: "nightlife",label: "Nightlife",      impact: "neutral",  note: "Indoor venues fully unaffected. Queuing outside is the only issue." },
        { key: "popups",   label: "Pop-ups",        impact: "negative", note: "All outdoor pop-ups cancelled or moved. Only indoor options remain." },
        { key: "outdoor",  label: "Outdoor events", impact: "negative", note: "Heavy wind and rain. All outdoor programming has closed or moved inside." },
      ],
    },
    safetyItems: [
      { id: "tn-sf1", type: "large-crowd",      typeLabel: "Large crowd",    area: "Granville",  description: "Granville Strip above 2,500 persons. Officers on foot patrol.", time: "After 10 PM", severity: "high" },
      { id: "tn-sf2", type: "police-activity",  typeLabel: "Police activity",area: "Downtown",   description: "Crowd management at Rogers Arena post-game. Expect Griffiths Way delays.", time: "10:30 PM – 11:30 PM", severity: "medium" },
      { id: "tn-sf3", type: "event-congestion", typeLabel: "Event congestion",area: "Granville", description: "Commodore Ballroom exit congestion. Granville St blocked at Robson until 10:15.", time: "10:00 PM – 10:30 PM", severity: "low" },
    ],
  },

  weekend: {
    timeBlocks: [
      { block: "morning",    label: "Morning",    hours: "6am – 12pm", count: 8  },
      { block: "afternoon",  label: "Afternoon",  hours: "12pm – 6pm", count: 18 },
      { block: "evening",    label: "Evening",    hours: "6pm – 10pm", count: 24 },
      { block: "late-night", label: "Late night", hours: "10pm – 2am", count: 16 },
    ],
    events: [
      { id: "we-m1", title: "Trout Lake farmers market",     venue: "Trout Lake Park",             area: "East Van",       timeBlock: "morning",    time: "9:00 AM" },
      { id: "we-m2", title: "Riley Park farmers market",     venue: "Riley Park",                  area: "Mount Pleasant", timeBlock: "morning",    time: "10:00 AM" },
      { id: "we-m3", title: "Granville Island market",       venue: "Granville Island",            area: "Kitsilano",      timeBlock: "morning",    time: "9:00 AM" },
      { id: "we-m4", title: "Spanish Banks beach run",       venue: "Spanish Banks",               area: "UBC",            timeBlock: "morning",    time: "8:00 AM" },
      { id: "we-m5", title: "Stanley Park cycling opens",    venue: "Stanley Park",                area: "Stanley Park",   timeBlock: "morning",    time: "6:00 AM" },
      { id: "we-m6", title: "Flea market Mt Pleasant",       venue: "Main St & 2nd",               area: "Mount Pleasant", timeBlock: "morning",    time: "10:00 AM" },
      { id: "we-m7", title: "Kits Pool outdoor swim",        venue: "Kitsilano Pool",              area: "Kitsilano",      timeBlock: "morning",    time: "7:00 AM" },
      { id: "we-m8", title: "Gastown brunch line opens",     venue: "Gastown restaurants",         area: "Gastown",        timeBlock: "morning",    time: "10:00 AM" },
      { id: "we-a1", title: "Robson Square skate park",      venue: "Robson Square",               area: "Downtown",       timeBlock: "afternoon",  time: "1:00 PM" },
      { id: "we-a2", title: "Granville Island buskers",      venue: "Granville Island",            area: "Kitsilano",      timeBlock: "afternoon",  time: "2:00 PM" },
      { id: "we-a3", title: "Kits Beach volleyball finals",  venue: "Kitsilano Beach",             area: "Kitsilano",      timeBlock: "afternoon",  time: "1:30 PM" },
      { id: "we-a4", title: "Commercial Drive street fair",  venue: "Commercial Drive",            area: "East Van",       timeBlock: "afternoon",  time: "12:00 PM" },
      { id: "we-a5", title: "Yaletown art market",           venue: "Mainland St · Yaletown",     area: "Yaletown",       timeBlock: "afternoon",  time: "12:00 PM" },
      { id: "we-a6", title: "UBC Museum of Anthropology",   venue: "MOA · UBC",                   area: "UBC",            timeBlock: "afternoon",  time: "1:00 PM" },
      { id: "we-a7", title: "Science World drop-in",         venue: "Science World",               area: "Mount Pleasant", timeBlock: "afternoon",  time: "11:00 AM" },
      { id: "we-a8", title: "Strathcona community garden",  venue: "Strathcona",                  area: "East Van",       timeBlock: "afternoon",  time: "2:30 PM" },
      { id: "we-a9", title: "East Van punk pop-up",          venue: "Commercial Drive",            area: "Commercial Dr",  timeBlock: "afternoon",  time: "3:00 PM" },
      { id: "we-a10", title: "Vintage clothing swap",        venue: "Mt Pleasant Community",      area: "Mount Pleasant", timeBlock: "afternoon",  time: "2:00 PM" },
      { id: "we-a11", title: "Pacific Spirit trail walk",    venue: "Pacific Spirit Park · UBC",  area: "UBC",            timeBlock: "afternoon",  time: "1:00 PM" },
      { id: "we-a12", title: "Chinatown weekend market",     venue: "Chinatown",                   area: "Downtown",       timeBlock: "afternoon",  time: "12:00 PM" },
      { id: "we-a13", title: "Seawall sunset ride",          venue: "Seawall · Yaletown entry",  area: "Downtown",       timeBlock: "afternoon",  time: "4:00 PM" },
      { id: "we-a14", title: "Granville public art tour",    venue: "South Granville",             area: "Granville",      timeBlock: "afternoon",  time: "2:00 PM" },
      { id: "we-a15", title: "Kitsilano brunch pop-up",      venue: "W 4th Ave",                  area: "Kitsilano",      timeBlock: "afternoon",  time: "11:00 AM" },
      { id: "we-a16", title: "Night market early entry",     venue: "Richmond Night Market",      area: "Richmond",       timeBlock: "afternoon",  time: "4:00 PM" },
      { id: "we-a17", title: "Record shop day · Zulu",       venue: "Zulu Records · Kits",        area: "Kitsilano",      timeBlock: "afternoon",  time: "12:00 PM" },
      { id: "we-a18", title: "Seabus day trip window",       venue: "Waterfront Station",         area: "Downtown",       timeBlock: "afternoon",  time: "3:00 PM" },
      { id: "we-e1", title: "Yuno b2b Sansibar",             venue: "Open Studios · Strathcona",  area: "East Van",       timeBlock: "evening",    time: "8:00 PM" },
      { id: "we-e2", title: "Commodore weekend headliner",   venue: "Commodore Ballroom",         area: "Granville",      timeBlock: "evening",    time: "8:00 PM" },
      { id: "we-e3", title: "Harbour cruise departs",        venue: "Harbour Ferries · Coal Harbour", area: "Downtown",  timeBlock: "evening",    time: "7:00 PM" },
      { id: "we-e4", title: "Granville Strip heats up",      venue: "Multiple venues",            area: "Granville",      timeBlock: "evening",    time: "9:00 PM" },
      { id: "we-e5", title: "Rooftop cinema screening",      venue: "Cineplex · Granville",       area: "Granville",      timeBlock: "evening",    time: "9:00 PM" },
      { id: "we-e6", title: "Comedy festival night 2",       venue: "The Improv Centre",          area: "Gastown",        timeBlock: "evening",    time: "7:30 PM" },
      { id: "we-e7", title: "Fox Cabaret DJ residency",      venue: "Fox Cabaret",                area: "Mount Pleasant", timeBlock: "evening",    time: "9:00 PM" },
      { id: "we-e8", title: "Neon Crane bar opening",        venue: "Chinatown",                  area: "Downtown",       timeBlock: "evening",    time: "6:00 PM" },
      { id: "we-e9", title: "Sunday night jazz",             venue: "Guilt & Co",                 area: "Gastown",        timeBlock: "evening",    time: "8:00 PM" },
      { id: "we-e10", title: "Granville Island show",        venue: "Revue Stage",                area: "Kitsilano",      timeBlock: "evening",    time: "8:00 PM" },
      { id: "we-e11", title: "Yaletown tapas crawl",         venue: "Yaletown",                   area: "Yaletown",       timeBlock: "evening",    time: "6:30 PM" },
      { id: "we-e12", title: "UBC film society screening",   venue: "Chan Centre · UBC",          area: "UBC",            timeBlock: "evening",    time: "7:00 PM" },
      { id: "we-e13", title: "Mt Pleasant art after dark",   venue: "East Side Culture Crawl",    area: "Mount Pleasant", timeBlock: "evening",    time: "6:00 PM" },
      { id: "we-e14", title: "Outdoor movie — Spanish Banks",venue: "Spanish Banks Beach",        area: "UBC",            timeBlock: "evening",    time: "8:30 PM" },
      { id: "we-e15", title: "Night cycling seawall",        venue: "Burrard Bridge start",       area: "Downtown",       timeBlock: "evening",    time: "8:00 PM" },
      { id: "we-e16", title: "Kits House party block event", venue: "Kitsilano Community",        area: "Kitsilano",      timeBlock: "evening",    time: "7:00 PM" },
      { id: "we-e17", title: "Open mic — Commercial Drive",  venue: "Café Deux Soleils",          area: "Commercial Dr",  timeBlock: "evening",    time: "9:00 PM" },
      { id: "we-e18", title: "Late-night sushi bar",         venue: "Robson Street",              area: "Robson",         timeBlock: "evening",    time: "9:30 PM" },
      { id: "we-e19", title: "Taco pop-up · Gastown",        venue: "Blood Alley Square",         area: "Gastown",        timeBlock: "evening",    time: "6:00 PM" },
      { id: "we-e20", title: "Strathcona rave",              venue: "Venue TBA · Strathcona",     area: "East Van",       timeBlock: "evening",    time: "9:00 PM" },
      { id: "we-e21", title: "Rooftop bar Garden Terrace",   venue: "Garden Terrace · Downtown", area: "Downtown",       timeBlock: "evening",    time: "6:00 PM" },
      { id: "we-e22", title: "Vancouver symphony pop",       venue: "Orpheum Theatre",            area: "Downtown",       timeBlock: "evening",    time: "7:30 PM" },
      { id: "we-e23", title: "Night kayak group",            venue: "Granville Island launch",    area: "Kitsilano",      timeBlock: "evening",    time: "8:30 PM" },
      { id: "we-e24", title: "Comedy club walk-in",          venue: "Yuk Yuk's · Downtown",      area: "Downtown",       timeBlock: "evening",    time: "9:00 PM" },
      { id: "we-l1", title: "Commodore afterparty",          venue: "Venue Nightclub",            area: "Granville",      timeBlock: "late-night", time: "11:30 PM" },
      { id: "we-l2", title: "Granville Strip full capacity", venue: "Multiple venues",            area: "Granville",      timeBlock: "late-night", time: "11:00 PM" },
      { id: "we-l3", title: "Late night pho",                venue: "Pho Bich Nga · Downtown",   area: "Downtown",       timeBlock: "late-night", time: "11:30 PM" },
      { id: "we-l4", title: "Afterhours",                    venue: "Celebrities Nightclub",      area: "Downtown",       timeBlock: "late-night", time: "12:00 AM" },
      { id: "we-l5", title: "DJ Hessle Audio",               venue: "Fox Cabaret",                area: "Mount Pleasant", timeBlock: "late-night", time: "12:00 AM" },
      { id: "we-l6", title: "Strathcona warehouse party",    venue: "Strathcona",                 area: "East Van",       timeBlock: "late-night", time: "11:00 PM" },
      { id: "we-l7", title: "Late-night Korean BBQ",         venue: "Robson Street",              area: "Robson",         timeBlock: "late-night", time: "12:00 AM" },
      { id: "we-l8", title: "2am dim sum opens",             venue: "Aberdeen Mall · Richmond",  area: "Richmond",       timeBlock: "late-night", time: "2:00 AM" },
      { id: "we-l9", title: "Gastown bar crawl ends",        venue: "Various · Gastown",          area: "Gastown",        timeBlock: "late-night", time: "2:00 AM" },
      { id: "we-l10", title: "UBC party circuit",            venue: "UBC student housing",        area: "UBC",            timeBlock: "late-night", time: "11:00 PM" },
      { id: "we-l11", title: "Kits late-night bottle shop",  venue: "Kitsilano",                  area: "Kitsilano",      timeBlock: "late-night", time: "11:00 PM" },
      { id: "we-l12", title: "Chinatown late food crawl",    venue: "Chinatown",                  area: "Downtown",       timeBlock: "late-night", time: "12:30 AM" },
      { id: "we-l13", title: "Neon lights walk downtown",    venue: "Robson to Granville",        area: "Downtown",       timeBlock: "late-night", time: "11:00 PM" },
      { id: "we-l14", title: "Last SkyTrain departs",        venue: "Waterfront Station",         area: "Downtown",       timeBlock: "late-night", time: "1:07 AM" },
      { id: "we-l15", title: "Biltmore late programme",      venue: "Biltmore Cabaret",           area: "Mount Pleasant", timeBlock: "late-night", time: "11:30 PM" },
      { id: "we-l16", title: "Mount Pleasant closing time",  venue: "Main St bars",               area: "Mount Pleasant", timeBlock: "late-night", time: "2:00 AM" },
    ],
    categoryStats: [
      { key: "trending",  label: "Trending",  count: 38, description: "Highest city-wide activity of the week. Every neighbourhood busy. Markets, events, and nightlife all peaking." },
      { key: "nightlife", label: "Nightlife", count: 32, description: "Bars, shows, clubs, late food. Full capacity expected across Granville, Downtown, and Mt Pleasant from 9pm." },
      { key: "cafes",     label: "Cafes",     count: 18, description: "Coffee, brunch, bakeries. Kits and Gastown brunch lines early. Afternoon coffee demand steady." },
      { key: "popups",    label: "Pop-ups",   count: 12, description: "Markets, drops, temporary events. Multiple farmers markets and street fairs active all weekend." },
    ],
    weather: {
      condition: "Partly cloudy",
      conditionCode: "partly-cloudy",
      temperature: 17,
      rainChance: 25,
      windSpeed: 12,
      visibility: "15 km",
      outdoorEventImpact: "low",
      hourlyForecast: [
        { hour: "12 PM", temp: 16, conditionCode: "partly-cloudy" },
        { hour: "2 PM",  temp: 17, conditionCode: "clear"          },
        { hour: "4 PM",  temp: 17, conditionCode: "clear"          },
        { hour: "6 PM",  temp: 16, conditionCode: "partly-cloudy" },
        { hour: "8 PM",  temp: 15, conditionCode: "overcast"       },
        { hour: "10 PM", temp: 14, conditionCode: "overcast"       },
      ],
      affectedAreas: [],
      categoryImpacts: [
        { key: "cafes",    label: "Cafes",          impact: "neutral",  note: "Good conditions. Normal brunch and coffee demand. Markets drawing crowd away from indoor spots." },
        { key: "nightlife",label: "Nightlife",      impact: "positive", note: "Good weather keeps people out longer. Patio venues and outdoor bars fully open." },
        { key: "popups",   label: "Pop-ups",        impact: "positive", note: "Ideal market weather. Farmers markets and flea markets fully operational all weekend." },
        { key: "outdoor",  label: "Outdoor events", impact: "positive", note: "Low impact. Parks, beaches, seawall, and cycling paths all good. Best weekend of the month." },
      ],
    },
    safetyItems: [
      { id: "we-sf1", type: "event-congestion", typeLabel: "Event congestion", area: "Kitsilano",    description: "Granville Island market at peak weekend capacity. Parking full by 10am. Take transit.", time: "9 AM – 3 PM", severity: "medium" },
      { id: "we-sf2", type: "large-crowd",      typeLabel: "Large crowd",      area: "East Van",     description: "Commercial Drive street fair closes two blocks. Expect foot traffic on side streets.", time: "12 PM – 6 PM", severity: "low" },
    ],
  },

  transitRoutes: [
    {
      id: "tr1",
      name: "Expo Line",
      shortName: "Expo",
      delayLevel: "moderate",
      delayMinutes: 15,
      affectedStation: "Stadium–Chinatown",
      affectedArea: "Downtown",
      disruptionType: "Rogers Arena event congestion",
      until: "11:30 PM",
      stationsBefore: 3,
      stationsAfter: 3,
    },
    {
      id: "tr2",
      name: "99 B-Line",
      shortName: "99 B",
      delayLevel: "severe",
      delayMinutes: 0,
      affectedStation: "Granville at Broadway",
      affectedArea: "Granville",
      disruptionType: "Single-direction closure",
      until: "2:00 AM",
      stationsBefore: 1,
      stationsAfter: 3,
    },
    {
      id: "tr3",
      name: "Granville Bridge",
      shortName: "Bridge",
      delayLevel: "minor",
      delayMinutes: 5,
      affectedStation: "Granville Bridge midspan",
      affectedArea: "Granville",
      disruptionType: "Lane closure – overnight construction",
      until: "6:00 AM",
      stationsBefore: 0,
      stationsAfter: 0,
    },
    {
      id: "tr4",
      name: "Seabus",
      shortName: "Seabus",
      delayLevel: "minor",
      delayMinutes: 0,
      affectedStation: "Waterfront Terminal",
      affectedArea: "Downtown",
      disruptionType: "Last departure 1:15 AM — no overnight",
      until: "1:15 AM",
      stationsBefore: 0,
      stationsAfter: 1,
    },
  ],

  postsByHour: {
    today: [
      { hour: 0, count: 11 }, { hour: 1, count: 7 },  { hour: 2, count: 4 },
      { hour: 3, count: 3 },  { hour: 4, count: 2 },  { hour: 5, count: 5 },
      { hour: 6, count: 10 }, { hour: 7, count: 19 }, { hour: 8, count: 30 },
      { hour: 9, count: 34 }, { hour: 10, count: 28 },{ hour: 11, count: 33 },
      { hour: 12, count: 41 },{ hour: 13, count: 37 },{ hour: 14, count: 30 },
      { hour: 15, count: 26 },{ hour: 16, count: 34 },{ hour: 17, count: 42 },
      { hour: 18, count: 49 },{ hour: 19, count: 54 },{ hour: 20, count: 60 },
      { hour: 21, count: 63 },{ hour: 22, count: 56 },{ hour: 23, count: 39 },
    ],
    tonight: [
      { hour: 0, count: 14 }, { hour: 1, count: 9 },  { hour: 2, count: 5 },
      { hour: 3, count: 3 },  { hour: 4, count: 2 },  { hour: 5, count: 5 },
      { hour: 6, count: 10 }, { hour: 7, count: 19 }, { hour: 8, count: 30 },
      { hour: 9, count: 34 }, { hour: 10, count: 28 },{ hour: 11, count: 33 },
      { hour: 12, count: 41 },{ hour: 13, count: 37 },{ hour: 14, count: 30 },
      { hour: 15, count: 26 },{ hour: 16, count: 34 },{ hour: 17, count: 44 },
      { hour: 18, count: 52 },{ hour: 19, count: 58 },{ hour: 20, count: 67 },
      { hour: 21, count: 72 },{ hour: 22, count: 68 },{ hour: 23, count: 51 },
    ],
    weekend: [
      { hour: 0, count: 28 }, { hour: 1, count: 22 }, { hour: 2, count: 15 },
      { hour: 3, count: 9 },  { hour: 4, count: 5 },  { hour: 5, count: 7 },
      { hour: 6, count: 11 }, { hour: 7, count: 16 }, { hour: 8, count: 22 },
      { hour: 9, count: 31 }, { hour: 10, count: 38 },{ hour: 11, count: 44 },
      { hour: 12, count: 51 },{ hour: 13, count: 55 },{ hour: 14, count: 52 },
      { hour: 15, count: 48 },{ hour: 16, count: 50 },{ hour: 17, count: 57 },
      { hour: 18, count: 65 },{ hour: 19, count: 72 },{ hour: 20, count: 81 },
      { hour: 21, count: 88 },{ hour: 22, count: 84 },{ hour: 23, count: 70 },
    ],
  },

  areaStats: [
    { key: "downtown",       label: "Downtown",    events: 18, food: 15, nightlife: 22, safety: 4, transit: 3, total: 62 },
    { key: "granville",      label: "Granville",   events: 12, food: 8,  nightlife: 20, safety: 3, transit: 2, total: 45 },
    { key: "gastown",        label: "Gastown",     events: 8,  food: 12, nightlife: 15, safety: 2, transit: 1, total: 38 },
    { key: "robson",         label: "Robson",      events: 10, food: 9,  nightlife: 12, safety: 2, transit: 1, total: 34 },
    { key: "kitsilano",      label: "Kitsilano",   events: 6,  food: 14, nightlife: 5,  safety: 1, transit: 1, total: 27 },
    { key: "mount-pleasant", label: "Mt Pleasant", events: 5,  food: 11, nightlife: 8,  safety: 1, transit: 0, total: 25 },
    { key: "ubc",            label: "UBC",         events: 7,  food: 6,  nightlife: 2,  safety: 0, transit: 2, total: 17 },
    { key: "stanley-park",   label: "Stanley Park",events: 3,  food: 0,  nightlife: 0,  safety: 0, transit: 0, total: 5  },
  ],
};
